name: Rust

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install checkers and linters
        run: |
          rustup component add rustfmt
          rustup component add clippy
      - name: Check Formatting
        run: cargo fmt --all -- --check
      - name: Check Idiomatic
        run: cargo clippy --all --all-features -- -D warnings
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
